#!/usr/bin/env python3
"""Build a navigable index for _SILENT_FAILURES.md.

The file is the main intellectual artefact of this project: 415 numbered
findings over 26,000 lines. It is written in the order things were discovered,
which is the right order to write it in and the wrong order to look things up
in. Without an index the only way to find "the one about suppression keys" is
to remember roughly when it happened.

This regenerates the index from the file itself, so it cannot drift. Run it
after adding entries.

Themes are assigned by keyword against the section TITLE only -- deliberately,
because a title is short and written to be descriptive, whereas matching
against the body is the mistake catalogued four times in one day (SF 410): a
regex over free text measures the writer's vocabulary, not the world. An entry
can appear under several themes, and an entry that matches none is listed under
Other rather than being dropped.
"""
import re
import sys
from collections import OrderedDict

SRC = "brokers/_SILENT_FAILURES.md"
OUT = "brokers/_SILENT_FAILURES_INDEX.md"

THEMES = OrderedDict([
    ("Routes that resolve but do not work",
     r"route|url|redirect|form|404|link|page|portal|widget|button|click|captcha"),
    ("Confirmations that do not confirm",
     r"confirm|receipt|nil|answer|ticket|complete|resolved|success|status"),
    ("Suppression, deletion and durability",
     r"suppress|delet|durab|rebuild|persist|re-?add|survive|key"),
    ("Identifiers and what not to hand over",
     r"identifier|maid|device|cookie|ip |hash|reset|match|search"),
    ("Who actually holds the data",
     r"source|supplier|upstream|reseller|affiliate|acquisition|successor|"
     r"controller|family|sibling|broker"),
    ("Reaching a company at all",
     r"address|mailbox|bounce|email|contact|unreachable|domain|deliver"),
    ("My own errors and instruments",
     r"scanner|classifier|audit|instrument|my own|count|over-?report|"
     r"undercount|wrong|corrected|ledger"),
])


def main():
    try:
        lines = open(SRC, encoding="utf-8").read().split("\n")
    except FileNotFoundError:
        sys.exit(f"{SRC} not found")

    entries = []
    for i, ln in enumerate(lines, 1):
        # TWO HEADING STYLES, and the first version of this script knew only
        # one. Entries 1-44 and roughly 350+ are written "## 12. Title";
        # everything between is "## §57 Title". Matching only the first found
        # 74 of 415 and would have shipped an index covering a sixth of the
        # file. Same failure as SF 410, caught the same way -- by looking at
        # what was not matched instead of trusting the count.
        m = (re.match(r"^##\s+(\d+[a-z]?)\.\s+(.+?)\s*$", ln) or
             re.match(r"^##\s+§\s*(\d+[a-z]?)\s+(.+?)\s*$", ln))
        if m:
            entries.append((m.group(1), m.group(2), i))
            continue
        # A THIRD STYLE: "## §109" alone, with the title on a following line.
        # Found by listing what the previous two patterns did NOT match, which
        # is the only reliable way to discover a format nobody documented.
        bare = re.match(r"^##\s+§\s*(\d+[a-z]?)\s*$", ln)
        if bare:
            title = ""
            for nxt in lines[i:i + 4]:
                t = nxt.strip().lstrip("#").strip()
                if t:
                    title = t
                    break
            entries.append((bare.group(1), title or "(untitled)", i))

    if not entries:
        sys.exit("no numbered sections found")

    themed = {t: [] for t in THEMES}
    other = []
    for num, title, line in entries:
        hit = False
        for theme, pat in THEMES.items():
            if re.search(pat, title, re.I):
                themed[theme].append((num, title, line))
                hit = True
        if not hit:
            other.append((num, title, line))

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("# Index to the silent-failures file\n\n")
        f.write(f"{len(entries)} findings across {len(lines):,} lines. "
                "Generated by `scripts/index_failures.py` — do not edit by "
                "hand, regenerate it.\n\n")
        f.write("The file itself is chronological, which is the right order "
                "to write findings in and the wrong order to look them up "
                "in. An entry appears under every theme its title matches.\n\n")

        for theme in THEMES:
            rows = themed[theme]
            if not rows:
                continue
            f.write(f"## {theme}  ({len(rows)})\n\n")
            for num, title, line in rows:
                f.write(f"- **{num}** {title}  ·  L{line}\n")
            f.write("\n")

        if other:
            f.write(f"## Other  ({len(other)})\n\n")
            for num, title, line in other:
                f.write(f"- **{num}** {title}  ·  L{line}\n")
            f.write("\n")

        f.write("---\n\n## Every entry, in order\n\n")
        for num, title, line in entries:
            f.write(f"- **{num}** {title}  ·  L{line}\n")

    print(f"wrote {OUT}: {len(entries)} entries")
    for theme in THEMES:
        print(f"  {theme:42} {len(themed[theme])}")
    print(f"  {'Other':42} {len(other)}")


if __name__ == "__main__":
    main()
